const STATIC_MODE=Boolean(window.GALLERY_BOOTSTRAP);const state={indicators:[],series:[],charts:[],derived:[],derivedInputs:[],pipeline:null,seriesPayload:null,chartId:null,chartRenderSeq:0,editingDerivedId:null,viewerOrigin:'gallery',viewerChartId:null,seasonalColors:{},galleryPage:1,galleryPageSize:18,indicatorLimit:80,titleManuallyEdited:false,lastAutoTitle:'',showcase:new Set(JSON.parse(localStorage.getItem('yd-showcase')||'[]'))};
const $=id=>document.getElementById(id);const DEFAULT_TIMESERIES_START='2010-01-01';const freqLabel={daily:'日频',weekly:'周频',monthly:'月频',quarterly:'季频',annual:'年频',unknown:'未知'};
const fmt=v=>v==null?'—':Number(v).toLocaleString('zh-CN',{useGrouping:true,maximumFractionDigits:8});
const numOrNull=id=>$(id).value.trim()===''?null:Number($(id).value);const uid=()=>`S-${Date.now()}-${Math.random().toString(16).slice(2)}`;

async function getJSON(url,options){
  if(STATIC_MODE){const b=window.GALLERY_BOOTSTRAP;
    if(url==='/api/system')return b.system;if(url==='/api/indicators')return b.indicators;
    if(url==='/api/charts'&&options?.method==='POST'){const c=JSON.parse(options.body||'{}'),existing=localCharts(),n=existing.length+1,id=c.chart_id||`LOCAL-CH-${String(n).padStart(6,'0')}`,old=existing.find(x=>x.chart_id===id),preview=c.preview_data_url||old?.png_url||null,figure=c.preview_figure||old?.figure||null,reason=c._change_reason||'chart_save';delete c.preview_data_url;delete c.preview_figure;delete c._change_reason;const now=new Date().toISOString(),item={chart_id:id,title:c.title,domain:c.domain,status:c.status,access_level:c.access_level,config:{...c,chart_id:id},html_url:null,png_url:preview,figure,updated_at:now},history=JSON.parse(localStorage.getItem('yd-chart-range-history')||'[]');if(reason==='chart_range_update'){history.push({operated_at:now,chart_id:id,previous:old?.config||null,current:item.config});localStorage.setItem('yd-chart-range-history',JSON.stringify(history.slice(-500)))}localStorage.setItem('yd-local-charts',JSON.stringify([...existing.filter(x=>x.chart_id!==id),item]));return{chart_id:id,version:history.filter(x=>x.chart_id===id).length+1,preview_mode:true}}
    if(url==='/api/charts'){const merged=new Map((b.charts||[]).map(x=>[x.chart_id,x]));localCharts().forEach(x=>merged.set(x.chart_id,x));return[...merged.values()]}if(url==='/api/domains')return b.domains||[];if(url==='/api/derived'&&!options)return b.derived||[];if(url==='/api/pipeline')return b.pipeline||{raw_dir:b.system?.raw_dir,workbooks:[],identity_queue:[],source_snapshots:0,revision_count:0,pending_identities:0};
    if(url==='/api/run-import')throw new Error('公开在线版不读取原始 Excel；数据由袁丹研究图库发布者统一更新。');
    if(url==='/api/derived'&&options?.method==='POST')throw new Error('公开在线版暂不把派生指标写入共享数据库；可在画图工作台创建并保存本地图表。');
    if(url.startsWith('/api/series?')){const q=new URLSearchParams(url.split('?')[1]),ids=(q.get('ids')||'').split(',').filter(Boolean),start=q.get('start')||'0000-00-00',end=q.get('end')||'9999-99-99',metadata={},series={};await Promise.all(ids.map(id=>b.series?.[id]?Promise.resolve():loadStaticSeries(id,start,end)));ids.forEach(id=>{metadata[id]=b.indicators.find(x=>x.indicator_id===id);const direct=b.series?.[id];const yearly=window.GALLERY_SERIES_CACHE?.[id]||{};series[id]=(direct||Object.values(yearly).flat()).filter(p=>p.date>=start&&p.date<=end).sort((a,b)=>a.date.localeCompare(b.date))});return{metadata,series,spring_festival_dates:b.spring_festival_dates||{}}}
    if(url==='/api/run-import')throw new Error('离线预览不能更新数据，请启动完整工作台。');
  }
  const r=await fetch(url,options),contentType=r.headers.get('content-type')||'';let d;
  if(contentType.includes('application/json'))d=await r.json();
  else{const text=await r.text();throw new Error(r.ok?'服务器返回了无法识别的内容。':`服务器请求失败（${r.status}），请稍后重试。`)}
  if(!r.ok)throw new Error(d.error||`请求失败（${r.status}）`);return d;
}
const staticSeriesLoads=new Map();
function loadStaticSeries(indicatorId,start='0000-00-00',end='9999-99-99'){const manifest=window.GALLERY_BOOTSTRAP?.series_manifest?.[indicatorId];if(!manifest)return Promise.reject(new Error(`没有找到指标数据文件：${indicatorId}`));const fromYear=Number(String(start).slice(0,4))||0,toYear=Number(String(end).slice(0,4))||9999,years=Object.keys(manifest).filter(y=>Number(y)>=fromYear&&Number(y)<=toYear);return Promise.all(years.map(year=>{if(window.GALLERY_SERIES_CACHE?.[indicatorId]?.[year])return Promise.resolve();const key=`${indicatorId}|${year}`;if(staticSeriesLoads.has(key))return staticSeriesLoads.get(key);const promise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=new URL(`series/${manifest[year]}`,window.GALLERY_ASSET_BASE).href;script.async=true;script.onload=()=>resolve();script.onerror=()=>reject(new Error(`指标数据加载失败：${indicatorId} · ${year}`));document.head.appendChild(script)});staticSeriesLoads.set(key,promise);return promise}))}
function localCharts(){return JSON.parse(localStorage.getItem('yd-local-charts')||'[]')}

async function initialize(){
  const [system,indicators,charts,domains,derived,pipeline]=await Promise.all([getJSON('/api/system'),getJSON('/api/indicators'),getJSON('/api/charts'),getJSON('/api/domains'),getJSON('/api/derived'),getJSON('/api/pipeline')]);
  state.indicators=indicators;state.charts=charts;state.derived=derived;state.pipeline=pipeline;hydrateLocalFigures();$('systemStats').textContent=`${system.indicator_count} 个指标 · ${Number(system.observation_count).toLocaleString()} 个有效观测 · ${STATIC_MODE?'公开在线模式':'正式模式'} · 最近导入 ${system.latest_run?.finished_at?.slice(0,16).replace('T',' ')||'—'}`;
  populateFilters(domains);renderDerivedInputs();renderDerivedSearch();renderDerived();renderPipeline();renderLibrary();renderGallery();renderShowcase();bindControls();
}
function populateFilters(domains){
  const all=[...new Set([...domains,...state.indicators.map(x=>x.domain).filter(Boolean),...state.charts.map(x=>x.domain).filter(Boolean)])].sort();
  {const el=$('domainFilter');while(el.options.length>1)el.remove(1);all.forEach(v=>el.add(new Option(v,v)))}
  $('domainOptions').innerHTML=all.map(v=>`<option value="${escapeHTML(v)}"></option>`).join('');
  while($('frequencyFilter').options.length>1)$('frequencyFilter').remove(1);
  [...new Set(state.indicators.map(x=>x.frequency).filter(Boolean))].forEach(v=>$('frequencyFilter').add(new Option(freqLabel[v]||v,v)));
  populateGalleryDomains();
}
function chartKind(c){if(c.config?.chart_mode==='seasonal'||c.config?.chart_mode==='seasonal_cny')return c.config.chart_mode;const s=c.config?.series||[];if(s.length<=1)return'single';return new Set(s.map(x=>x.axis||'left')).size>1?'dual':'multi'}
function defaultChartTitle(){const names=side=>state.series.filter(s=>(s.axis||'left')===side).map(s=>(s.label||s.indicator?.name||'').trim()).filter(Boolean),left=names('left'),right=names('right');if(left.length&&right.length)return`${left.join(' + ')} vs ${right.join(' + ')}`;const all=[...left,...right];return all.length?all.join(' + '):'未命名图表'}
function syncDefaultChartTitle(force=false){const input=$('chartTitle'),next=defaultChartTitle(),current=input.value.trim();if(force||!state.titleManuallyEdited||!current||current==='未命名图表'||current===state.lastAutoTitle){input.value=next;state.lastAutoTitle=next;state.titleManuallyEdited=false}}
function kindLabel(kind){return({single:'单序列',dual:'双轴图',multi:'多序列单轴',seasonal:'季节性图',seasonal_cny:'季节性图（春节对齐）'})[kind]||'未分类'}
function populateGalleryDomains(){const selected=$('galleryKind').value,current=$('galleryDomain').value,domains=[...new Set(state.charts.filter(c=>!selected||chartKind(c)===selected).map(c=>c.domain||'未分类'))].sort(),el=$('galleryDomain');while(el.options.length>1)el.remove(1);domains.forEach(v=>el.add(new Option(v,v)));el.value=domains.includes(current)?current:''}
function nextDerivedAlias(){const used=new Set(state.derivedInputs.map(x=>x.alias));for(let i=0;i<26;i++){const a=String.fromCharCode(65+i);if(!used.has(a))return a}let i=27;while(used.has(`X${i}`))i++;return`X${i}`}
function derivedCandidateText(x){return[x.name,x.indicator_id,x.external_id,x.publisher,x.source_system,x.domain,x.subdomain].join(' ').toLowerCase()}
function renderDerivedSearch(){const el=$('derivedSearchResults'),q=$('derivedIndicatorSearch').value.trim().toLowerCase();if(!q){el.innerHTML='<div class="indicator-meta">输入关键词后显示匹配指标；点击结果即可加入公式，可重复加入同一指标并设置不同变形。</div>';return}const rows=state.indicators.filter(x=>derivedCandidateText(x).includes(q)).slice(0,40);el.innerHTML=rows.map(x=>`<button class="factory-result" data-add-derived="${x.indicator_id}"><strong>${escapeHTML(x.name)}</strong><span>${x.indicator_id} · ${escapeHTML(x.publisher||x.source_system)} · ${freqLabel[x.frequency]||x.frequency}</span></button>`).join('')||'<div class="indicator-meta">没有匹配指标，请尝试名称、ID、来源或板块关键词。</div>';el.querySelectorAll('[data-add-derived]').forEach(b=>b.onclick=()=>{state.derivedInputs.push({key:uid(),alias:nextDerivedAlias(),indicator_id:b.dataset.addDerived,transform:'level',lag_periods:0});renderDerivedInputs()})}
function transformOptions(current){return[['level','原值'],['yoy','同比 %'],['mom','环比 %'],['qoq','季比 %'],['change','较上期变化'],['log','自然对数'],['log_return','对数变化 %'],['index100','首期=100']].map(([v,n])=>`<option value="${v}" ${current===v?'selected':''}>${n}</option>`).join('')}
function renderDerivedInputs(){const el=$('derivedInputs');el.innerHTML=state.derivedInputs.map(s=>{const m=state.indicators.find(x=>x.indicator_id===s.indicator_id);return`<div class="derived-input-row" data-key="${s.key}"><div class="derived-alias">${escapeHTML(s.alias)}</div><div class="derived-input-name">${escapeHTML(m?.name||s.indicator_id)}<div class="indicator-meta">${s.indicator_id} · ${escapeHTML(m?.publisher||m?.source_system||'')}</div></div><label>参与公式前变形<select class="derived-transform">${transformOptions(s.transform||'level')}</select></label><label>滞后期数<input class="derived-lag" type="number" min="0" max="10000" value="${Number(s.lag_periods)||0}"></label><button class="derived-remove" aria-label="移除公式输入">×</button></div>`}).join('')||'<div class="indicator-meta">尚未加入公式输入。先在上方搜索指标。</div>';el.querySelectorAll('.derived-input-row').forEach(row=>{const s=state.derivedInputs.find(x=>x.key===row.dataset.key);row.querySelector('.derived-transform').onchange=e=>s.transform=e.target.value;row.querySelector('.derived-lag').onchange=e=>s.lag_periods=Math.max(0,Number(e.target.value)||0);row.querySelector('.derived-remove').onclick=()=>{state.derivedInputs=state.derivedInputs.filter(x=>x.key!==s.key);renderDerivedInputs()}})}
function derivedConfig(){return{derived_id:state.editingDerivedId||undefined,name:$('derivedName').value.trim(),operation:$('derivedOperation').value,expression:$('derivedExpression').value.trim(),unit:$('derivedUnit').value.trim(),domain:$('derivedDomain').value.trim()||'派生指标',inputs:state.derivedInputs.map(({alias,indicator_id,transform,lag_periods})=>({alias,indicator_id,transform,lag_periods}))}}
function renderDerived(){$('derivedCount').textContent=`${state.derived.length} 个`;$('derivedList').innerHTML=state.derived.map(x=>`<div class="derived-item"><strong>${escapeHTML(x.name)}</strong><span>${x.indicator_id} · ${escapeHTML(x.operation)} · ${escapeHTML(x.frequency||'')} · ${escapeHTML(x.domain||'')}</span><button class="text-button" data-derived="${x.derived_id}">编辑公式</button></div>`).join('')||'<div class="indicator-meta">尚未构建派生指标。</div>';$('derivedList').querySelectorAll('[data-derived]').forEach(b=>b.onclick=()=>loadDerived(b.dataset.derived))}
function loadDerived(id){const item=state.derived.find(x=>x.derived_id===id);if(!item)return;const c=item.config||{};state.editingDerivedId=id;$('derivedName').value=item.name;$('derivedOperation').value=item.operation;$('derivedExpression').value=item.expression||c.expression||'';$('derivedUnit').value=item.unit||'';$('derivedDomain').value=item.domain||'派生指标';state.derivedInputs=(c.inputs||[]).map(x=>({...x,key:uid(),transform:x.transform||'level',lag_periods:Number(x.lag_periods)||0}));renderDerivedInputs();switchView('factory')}
function resetDerivedForm(){state.editingDerivedId=null;state.derivedInputs=[];$('derivedName').value='';$('derivedOperation').value='yoy';$('derivedExpression').value='';$('derivedUnit').value='';$('derivedDomain').value='派生指标';$('derivedIndicatorSearch').value='';renderDerivedInputs();renderDerivedSearch()}
function renderPipeline(){const p=state.pipeline||{workbooks:[],identity_queue:[]};$('pipelinePath').textContent=p.raw_dir||'—';$('pipelineStats').innerHTML=[['已入库指标',state.indicators.length.toLocaleString()],['有效观测',Number(p.observation_count||0).toLocaleString()],['原始文件快照',Number(p.source_snapshots||0).toLocaleString()],['历史修订留痕',Number(p.revision_count||0).toLocaleString()],['身份待确认',Number(p.pending_identities||0).toLocaleString()]].map(([n,v])=>`<div class="pipeline-stat"><span>${n}</span><strong>${v}</strong></div>`).join('');$('workbookStates').innerHTML=p.workbooks?.length?`<div class="pipeline-table-scroll"><table class="pipeline-table"><thead><tr><th>工作簿ID</th><th>最近模式</th><th>最近导入</th><th>最近完整审计</th><th>更新次数</th><th>增量回看</th></tr></thead><tbody>${p.workbooks.map(x=>`<tr><td>${escapeHTML(x.logical_workbook_id)}</td><td>${x.last_mode==='incremental'?'智能增量':'完整审计'}</td><td>${escapeHTML(String(x.last_imported_at||'—').slice(0,19).replace('T',' '))}</td><td>${escapeHTML(String(x.last_full_audit_at||'—').slice(0,10))}</td><td>${Number(x.update_count||0).toLocaleString()}</td><td>${Number(x.tail_days||400)}天</td></tr>`).join('')}</tbody></table></div>`:'<div class="pipeline-empty">首次更新后会显示每个Excel工作簿的增量状态。</div>';$('identityQueue').innerHTML=p.identity_queue?.length?`<div class="pipeline-table-scroll"><table class="pipeline-table"><thead><tr><th>待确认ID</th><th>来源</th><th>已有指标</th><th>新指标名称</th><th>来源ID</th><th>位置</th></tr></thead><tbody>${p.identity_queue.map(x=>`<tr><td>${escapeHTML(x.review_id)}</td><td>${escapeHTML(x.source_system)}</td><td>${escapeHTML(x.existing_name||'—')}<br><span class="indicator-meta">${escapeHTML(x.existing_indicator_id||'')}</span></td><td>${escapeHTML(x.incoming_name)}</td><td>${escapeHTML(x.external_id||'—')}</td><td>${escapeHTML(x.source_sheet)} · ${x.source_column}</td></tr>`).join('')}</tbody></table></div>`:'<div class="pipeline-empty">当前没有身份冲突。严格匹配成功的更新会自动归入原指标ID。</div>'}
async function reloadAll(){const [system,indicators,charts,domains,derived,pipeline]=await Promise.all([getJSON('/api/system'),getJSON('/api/indicators'),getJSON('/api/charts'),getJSON('/api/domains'),getJSON('/api/derived'),getJSON('/api/pipeline')]);state.indicators=indicators;state.charts=charts;state.derived=derived;state.pipeline=pipeline;hydrateLocalFigures();$('systemStats').textContent=`${system.indicator_count} 个指标 · ${Number(system.observation_count).toLocaleString()} 个有效观测 · ${STATIC_MODE?'公开在线模式':'正式模式'} · 最近导入 ${system.latest_run?.finished_at?.slice(0,16).replace('T',' ')||'—'}`;populateFilters(domains);renderDerivedSearch();renderDerivedInputs();renderDerived();renderPipeline();renderLibrary();renderGallery();renderShowcase()}
function switchView(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`${view}View`));document.querySelectorAll('.nav-button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));if(view==='gallery')renderGallery();if(view==='factory')renderDerived();if(view==='pipeline')renderPipeline();if(view==='showcase')renderShowcase()}
function filteredIndicators(){const q=$('search').value.trim().toLowerCase(),d=$('domainFilter').value,f=$('frequencyFilter').value;return state.indicators.filter(x=>{const h=[x.name,x.indicator_id,x.external_id,x.publisher,x.source_system].join(' ').toLowerCase();return(!q||h.includes(q))&&(!d||x.domain===d)&&(!f||x.frequency===f)})}
function renderLibrary(){const all=filteredIndicators(),rows=all.slice(0,state.indicatorLimit);$('resultCount').textContent=`显示 ${rows.length} / ${all.length}`;$('indicatorList').innerHTML=rows.map(x=>`<label class="indicator-item"><input type="checkbox" data-id="${x.indicator_id}" ${state.series.some(s=>s.indicator.indicator_id===x.indicator_id)?'checked':''}><span><span class="indicator-name">${escapeHTML(x.name)}</span><span class="indicator-meta">${x.indicator_id} · ${freqLabel[x.frequency]||x.frequency} · ${escapeHTML(x.unit||'无单位')}<br>${x.first_date||'—'} → ${x.latest_date||'—'}</span></span></label>`).join('');$('indicatorList').querySelectorAll('input').forEach(el=>el.onchange=()=>toggleIndicator(el.dataset.id,el.checked));$('indicatorMore').hidden=rows.length>=all.length}
function newSeries(indicator,base={}){return{series_key:uid(),indicator,axis:base.axis||((state.series.length===0)?'left':'right'),chart_type:base.chart_type||'line',ma_days:base.ma_days||1,shift_days:Number(base.shift_days)||0,start_date:base.start_date||indicator.first_date||DEFAULT_TIMESERIES_START,end_date:base.end_date||indicator.latest_date,end_mode:base.end_mode||'latest',label:base.label||''}}
function toggleIndicator(id,checked){const indicator=state.indicators.find(x=>x.indicator_id===id);if(checked&&!state.series.some(s=>s.indicator.indicator_id===id)){if(state.series.length>=12)return showMessage('一次最多12条序列。',true);state.series.push(newSeries(indicator))}else if(!checked)state.series=state.series.filter(s=>s.indicator.indicator_id!==id);state.chartId=null;renderSelected();syncDefaultChartTitle();updateDateDefaults();renderLibrary();refreshChart()}
function renderSelected(){$('selectedSeries').innerHTML=state.series.map(s=>`<div class="series-row" data-key="${s.series_key}"><div class="series-name">${escapeHTML(s.label||s.indicator.name)}<small>${s.indicator.indicator_id} · ${escapeHTML(s.indicator.publisher||s.indicator.source_system)}</small></div><select class="axis-select"><option value="left" ${s.axis==='left'?'selected':''}>左轴</option><option value="right" ${s.axis==='right'?'selected':''}>右轴</option></select><select class="type-select"><option value="line" ${s.chart_type==='line'?'selected':''}>折线</option><option value="bar" ${s.chart_type==='bar'?'selected':''}>柱形</option></select><label class="mini-field">MA天数<input class="ma-input" type="number" min="1" value="${s.ma_days}"></label><label class="mini-field">领先/滞后天数<input class="shift-input" type="number" step="1" value="${s.shift_days||0}" title="正数=领先，负数=滞后"></label><label class="mini-field">序列开始<input class="series-start" type="date" value="${s.start_date||''}"></label><label class="mini-field">结束方式<select class="series-end-mode"><option value="latest" ${s.end_mode==='latest'?'selected':''}>最新</option><option value="fixed" ${s.end_mode==='fixed'?'selected':''}>固定</option></select></label><label class="mini-field">序列结束<input class="series-end" type="date" value="${s.end_date||''}"></label><button class="series-copy" aria-label="复制序列">＋</button><button class="series-remove" aria-label="移除序列">×</button></div>`).join('')||'<div class="indicator-meta">尚未选择指标。</div>';
  $('selectedSeries').querySelectorAll('.series-row').forEach(row=>{const s=state.series.find(x=>x.series_key===row.dataset.key);row.querySelector('.axis-select').onchange=e=>{s.axis=e.target.value;syncDefaultChartTitle();refreshChart()};row.querySelector('.type-select').onchange=e=>{s.chart_type=e.target.value;refreshChart()};row.querySelector('.ma-input').onchange=e=>{s.ma_days=Math.max(1,Number(e.target.value)||1);refreshChart()};row.querySelector('.shift-input').onchange=e=>{s.shift_days=Math.trunc(Number(e.target.value)||0);e.target.value=s.shift_days;refreshChart()};row.querySelector('.series-start').onchange=e=>{s.start_date=e.target.value;refreshChart()};row.querySelector('.series-end-mode').onchange=e=>{s.end_mode=e.target.value;refreshChart()};row.querySelector('.series-end').onchange=e=>{s.end_mode='fixed';s.end_date=e.target.value;row.querySelector('.series-end-mode').value='fixed';refreshChart()};row.querySelector('.series-copy').onclick=()=>{if(state.series.length>=12)return showMessage('一次最多12条序列。',true);state.series.push(newSeries(s.indicator,{...s,axis:s.axis==='left'?'right':'left'}));renderSelected();syncDefaultChartTitle();refreshChart()};row.querySelector('.series-remove').onclick=()=>{state.series=state.series.filter(x=>x.series_key!==s.series_key);renderSelected();syncDefaultChartTitle();renderLibrary();refreshChart()}})}
function updateDateDefaults(){if(!state.series.length)return;const latest=state.series.map(x=>x.indicator.latest_date).filter(Boolean).sort().at(-1);if(!$('endDate').value)$('endDate').value=latest;if(!$('startDate').value)$('startDate').value=DEFAULT_TIMESERIES_START;$('endMode').value=$('endMode').value||'latest'}
function resolvedEndDate(){const a=state.series.map(x=>x.indicator).filter(x=>x.latest_date);if(!a.length)return $('endDate').value;if($('endMode').value==='latest')return a.map(x=>x.latest_date).sort().at(-1);if($('endMode').value==='common')return a.map(x=>x.latest_date).sort()[0];return $('endDate').value}
function moving(points,n){if(n<=1)return points;const w=[];return points.map(p=>{w.push(Number(p.value));if(w.length>n)w.shift();const v=w.reduce((a,b)=>a+b,0)/w.length;return{...p,value:v,value_display:fmt(v)}})}
function shiftedDate(date,days){const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+Number(days||0));return d.toISOString().slice(0,10)}
function shiftLabel(days){const n=Number(days||0);return n>0?` · 领先${n}天`:n<0?` · 滞后${Math.abs(n)}天`:''}
function effectiveTimeRange(start,end,series=state.series,mode=$('endMode').value){if(!start||!end||mode==='fixed')return{start,end};const shifts=series.map(s=>Number(s.shift_days)||0),minShift=Math.min(0,...shifts),maxShift=Math.max(0,...shifts);return{start:shiftedDate(start,minShift),end:shiftedDate(end,maxShift)}}
function pointsInViewport(points,start,end){return points.filter(p=>(!start||p.date>=start)&&(!end||p.date<=end))}
function storedAxis(settings={},right=false){const a={fixedrange:false,autorange:settings.reverse?'reversed':true,zeroline:false,separatethousands:true,exponentformat:'none',showexponent:'none',automargin:true,tickformat:',.8~f'};if(settings.min!=null&&settings.max!=null){a.range=settings.reverse?[settings.max,settings.min]:[settings.min,settings.max];a.autorange=false}if(right){a.overlaying='y';a.side='right'}return a}
function smartDateAxis(start,end,width=window.innerWidth,seasonal=false,interval='auto'){if(seasonal)return{tickformat:'%m-%d',tickangle:0,nticks:12,showgrid:false,automargin:true};const a=start?new Date(`${start}T00:00:00`):null,b=end?new Date(`${end}T00:00:00`):null,days=a&&b?Math.max(1,(b-a)/86400000):0,months={"6m":6,"1y":12,"2y":24,"5y":60}[interval];const axis={tickformat:'%y-%m',tickangle:width<620&&days<730?-45:0,showgrid:false,automargin:true};if(months){axis.dtick=`M${months}`;axis.tick0='2000-01-01'}else axis.nticks=width<620?6:days>3650?8:10;return axis}
function axisUnitForChart(c,side){const units=[...new Set((c.config?.series||[]).filter(s=>(s.axis||'left')===side).map(s=>state.indicators.find(i=>i.indicator_id===s.indicator_id)?.unit).filter(Boolean))];return units.length===1?units[0]:units.length>1?'多单位':''}
function hydrateLocalFigures(){if(!STATIC_MODE)return;const source=window.GALLERY_BOOTSTRAP.series||{};state.charts.forEach(c=>{if(c.html_url||c.figure||!c.config?.series?.length)return;const config=c.config;if(config.chart_mode==='seasonal'){const s=config.series[0],m=state.indicators.find(x=>x.indicator_id===s.indicator_id),all=moving(source[s.indicator_id]||[],s.ma_days||1),available=[...new Set(all.map(p=>Number(p.date.slice(0,4))))].sort((a,b)=>b-a),years=(config.seasonal_years?.length?config.seasonal_years:available.slice(0,5)).map(Number).sort((a,b)=>b-a),other=['#7f8c8d','#9467bd','#17becf','#8c564b','#e377c2','#bcbd22'];c.figure={data:years.map((year,i)=>{const pts=all.filter(p=>Number(p.date.slice(0,4))===year),color=i===0?'red':i===1?'blue':i===2?'green':other[(i-3)%other.length];return{x:pts.map(p=>`2000-${p.date.slice(5)}`),y:pts.map(p=>p.value),name:String(year),type:'scatter',mode:'lines',showlegend:true,line:{color,width:i===0?4:i<3?2.8:1.5},customdata:pts.map(p=>[p.date,p.value_display||fmt(p.value),m?.indicator_id,m?.unit,m?.source_system]),hovertemplate:'%{customdata[0]}<br>'+year+'：%{customdata[1]} '+(m?.unit||'')+'<extra></extra>'}}),layout:{margin:{l:62,r:28,t:42,b:58},hovermode:'closest',showlegend:true,legend:{orientation:'h',y:1.02,yanchor:'bottom'},xaxis:{range:['2000-01-01','2000-12-31'],tickformat:'%m-%d',tickangle:-90,automargin:true},yaxis:storedAxis(config.left_axis),plot_bgcolor:'#fff',paper_bgcolor:'#fff'}}}else{c.figure={data:config.series.map(s=>{const m=state.indicators.find(x=>x.indicator_id===s.indicator_id),end=s.end_mode==='latest'?m?.latest_date:s.end_date,pts=moving((source[s.indicator_id]||[]).filter(p=>(!s.start_date||p.date>=s.start_date)&&(!end||p.date<=end)),s.ma_days||1),color=s.axis==='right'?'red':'blue',name=(s.label||m?.name||s.indicator_id)+((s.ma_days||1)>1?` · MA${s.ma_days}`:'');return{x:pts.map(p=>p.date),y:pts.map(p=>p.value),name,type:s.chart_type==='bar'?'bar':'scatter',mode:s.chart_type==='bar'?undefined:'lines',showlegend:true,line:{color,width:s.axis==='right'?2:2.5},marker:{color},yaxis:s.axis==='right'?'y2':'y',customdata:pts.map(p=>[p.value_display||fmt(p.value),m?.indicator_id,m?.unit,m?.source_system]),hovertemplate:'%{x|%Y-%m-%d}<br>'+name+'：%{customdata[0]} '+(m?.unit||'')+'<extra></extra>'}}),layout:{margin:{l:64,r:64,t:42,b:58},hovermode:'x unified',showlegend:true,legend:{orientation:'h',y:1.02,yanchor:'bottom'},xaxis:{range:[config.start_date||null,config.end_date||null],tickformat:'%y-%m',tickangle:-90,automargin:true},yaxis:storedAxis(config.left_axis),yaxis2:storedAxis(config.right_axis,true),plot_bgcolor:'#fff',paper_bgcolor:'#fff'}}}})}
function selectedSeasonalYears(){return[...$('seasonalYears').selectedOptions].map(x=>Number(x.value)).filter(Number.isFinite)}
function selectedSeasonalHighlights(){return[...$('seasonalHighlightYears').selectedOptions].map(x=>Number(x.value)).filter(Number.isFinite)}
function seasonalDefaultColor(year,years){const ordered=[...years].sort((a,b)=>b-a),i=ordered.indexOf(Number(year)),palette=['#ff0000','#0000ff','#008000','#9467bd','#17becf','#e377c2','#bcbd22','#8c564b'];return palette[(i<0?0:i)%palette.length]}
function populateSeasonalYears(points){const years=[...new Set(points.map(p=>Number(p.date.slice(0,4))))].sort((a,b)=>b-a),el=$('seasonalYears'),hi=$('seasonalHighlightYears'),pending=JSON.parse(el.dataset.pending||'[]'),pendingHi=JSON.parse(hi.dataset.pending||'[]'),current=selectedSeasonalYears(),currentHi=selectedSeasonalHighlights(),chosen=new Set(pending.length?pending:(current.length?current:years.slice(0,5))),highlights=new Set(pendingHi.length?pendingHi:(currentHi.length?currentHi:years.slice(0,3)));el.innerHTML=years.map(y=>`<option value="${y}" ${chosen.has(y)?'selected':''}>${y}</option>`).join('');hi.innerHTML=years.filter(y=>chosen.has(y)).map(y=>`<option value="${y}" ${highlights.has(y)?'selected':''}>${y}</option>`).join('');delete el.dataset.pending;delete hi.dataset.pending}
function renderSeasonalColorControls(){const style=$('seasonalStyle').value,years=selectedSeasonalYears().sort((a,b)=>b-a),visible=style==='band'?selectedSeasonalHighlights().sort((a,b)=>b-a):years,el=$('seasonalColorControls');el.innerHTML=visible.map(y=>{const color=state.seasonalColors[y]||seasonalDefaultColor(y,years);state.seasonalColors[y]=color;return`<label class="seasonal-color-item">${y}<input type="color" data-seasonal-color="${y}" value="${color}"></label>`}).join('')||'<span>尚未选择年份线</span>';el.querySelectorAll('[data-seasonal-color]').forEach(x=>x.oninput=()=>{state.seasonalColors[x.dataset.seasonalColor]=x.value;refreshChart()})}
function median(values){const a=[...values].sort((x,y)=>x-y),n=a.length;return n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2}
function annualFilled(points){const sorted=[...points].sort((a,b)=>a.date.localeCompare(b.date));if(!sorted.length)return[];const exact=new Map(sorted.map(p=>[p.date.slice(5),p])),first=sorted[0].date.slice(5),last=sorted.at(-1).date.slice(5),out=[];let carry=null;for(let d=new Date(Date.UTC(2000,0,1));d.getUTCFullYear()===2000;d.setUTCDate(d.getUTCDate()+1)){const key=d.toISOString().slice(5,10);if(exact.has(key))carry=exact.get(key);if(key>=first&&key<=last&&carry)out.push({...carry,date:`${sorted[0].date.slice(0,4)}-${key}`})}return out}
function isSeasonalMode(mode){return mode==='seasonal'||mode==='seasonal_cny'}
function springAligned(points,year,festivalDates,fill=false){const anchor=festivalDates?.[year];if(!anchor)return[];const anchorMs=Date.parse(`${anchor}T00:00:00Z`),raw=[...points].sort((a,b)=>a.date.localeCompare(b.date)).map(p=>({...p,aligned_day:Math.round((Date.parse(`${p.date}T00:00:00Z`)-anchorMs)/86400000)}));if(!fill||!raw.length)return raw;const exact=new Map(raw.map(p=>[p.aligned_day,p])),out=[];let carry=null;for(let day=raw[0].aligned_day;day<=raw.at(-1).aligned_day;day++){if(exact.has(day))carry=exact.get(day);if(carry)out.push({...carry,aligned_day:day})}return out}
function seasonalTraces(all,m,years,style,highlights,colors,showAverage,showMedian,alignment='calendar',festivalDates={}){const cny=alignment==='cny',byYear=new Map(years.map(y=>[y,all.filter(p=>Number(p.date.slice(0,4))===y)]));const aligned=(year,fill=false)=>cny?springAligned(byYear.get(year)||[],year,festivalDates,fill):(fill?annualFilled(byYear.get(year)||[]):(byYear.get(year)||[]));const lineForYear=(year,width=2.4)=>{const pts=aligned(year),color=colors[year]||seasonalDefaultColor(year,years);return{x:pts.map(p=>cny?p.aligned_day:`2000-${p.date.slice(5)}`),y:pts.map(p=>p.value),name:String(year),type:'scatter',mode:'lines',line:{color,width},customdata:pts.map(p=>[p.date,p.value_display||fmt(p.value)]),hovertemplate:'%{customdata[0]}<br>%{customdata[1]}<extra></extra>'}};if(style==='lines')return years.map((y,i)=>lineForYear(y,i===0?4:i<3?2.8:1.5));const grouped={};for(const y of years)for(const p of aligned(y,true)){const key=cny?p.aligned_day:p.date.slice(5);(grouped[key]??=[]).push(Number(p.value))}const keys=Object.keys(grouped).map(k=>cny?Number(k):k).sort(cny?((a,b)=>a-b):undefined),x=keys.map(k=>cny?k:`2000-${k}`),mins=keys.map(k=>Math.min(...grouped[k])),maxs=keys.map(k=>Math.max(...grouped[k])),avgs=keys.map(k=>grouped[k].reduce((a,b)=>a+b,0)/grouped[k].length),meds=keys.map(k=>median(grouped[k])),labels=keys.map(k=>cny?(Number(k)===0?'春节':`春节${Number(k)>0?'+':''}${k}天`):k),traces=[{x,y:mins,name:'Min–Max区间',type:'scatter',mode:'lines',line:{color:'rgba(128,128,128,0)',width:0},hoverinfo:'skip',showlegend:false},{x,y:maxs,name:'Min–Max区间',type:'scatter',mode:'lines',line:{color:'rgba(128,128,128,.45)',width:1},fill:'tonexty',fillcolor:'rgba(128,128,128,.22)',customdata:keys.map((k,i)=>[labels[i],fmt(mins[i]),fmt(maxs[i])]),hovertemplate:'%{customdata[0]}<br>Min：%{customdata[1]}<br>Max：%{customdata[2]}<extra></extra>'}];if(showAverage)traces.push({x,y:avgs,name:'平均值',type:'scatter',mode:'lines',line:{color:'#444444',width:2.6},customdata:keys.map((k,i)=>[labels[i],fmt(avgs[i])]),hovertemplate:'%{customdata[0]}<br>%{customdata[1]}<extra></extra>'});if(showMedian)traces.push({x,y:meds,name:'中位数',type:'scatter',mode:'lines',line:{color:'#777777',width:2,dash:'dash'},customdata:keys.map((k,i)=>[labels[i],fmt(meds[i])]),hovertemplate:'%{customdata[0]}<br>%{customdata[1]}<extra></extra>'});return traces.concat(highlights.filter(y=>years.includes(y)).map(y=>lineForYear(y,2.8)))}
function yAxis(side){const min=numOrNull(`${side}Min`),max=numOrNull(`${side}Max`),reverse=$(`${side}Reverse`).checked,units=[...new Set(state.series.filter(s=>s.axis===side).map(s=>s.indicator.unit).filter(Boolean))],title=units.length===1?units[0]:units.length>1?'多单位':'',a={fixedrange:false,autorange:reverse?'reversed':true,showgrid:side==='left',gridcolor:'#e8ebef',gridwidth:1,showline:false,zeroline:false,separatethousands:true,exponentformat:'none',showexponent:'none',automargin:true,tickformat:',.8~f',title:title?{text:title,standoff:8}:undefined};if(min!=null&&max!=null){a.range=reverse?[max,min]:[min,max];a.autorange=false}return a}
async function refreshChart(){if(STATIC_MODE)await ensurePublicPlotly();const renderSeq=++state.chartRenderSeq;if(!state.series.length){$('emptyState').style.display='grid';$('effectiveRangeNote').textContent='';Plotly.purge('chart');return}$('emptyState').style.display='none';const mode=$('chartMode').value,seasonal=isSeasonalMode(mode),cny=mode==='seasonal_cny';$('seasonalControls').hidden=!seasonal;if(seasonal)$('effectiveRangeNote').textContent=cny?'横轴以春节当天为第0天':'';const activeSeries=seasonal?[state.series[0]]:state.series,ids=[...new Set(activeSeries.map(s=>s.indicator.indicator_id))],start=seasonal?activeSeries[0].indicator.first_date:($('startDate').value||state.series.map(s=>s.start_date).filter(Boolean).sort()[0]),end=seasonal?activeSeries[0].indicator.latest_date:resolvedEndDate();if(!seasonal&&$('endMode').value!=='fixed')$('endDate').value=end;const payload=await getJSON(`/api/series?${new URLSearchParams({ids:ids.join(','),start,end})}`);if(renderSeq!==state.chartRenderSeq)return;state.seriesPayload=payload;
  let traces,layout;if(seasonal){const s=activeSeries[0],m=payload.metadata[s.indicator.indicator_id],all=moving(payload.series[s.indicator.indicator_id]||[],s.ma_days);populateSeasonalYears(all);const style=$('seasonalStyle').value,years=selectedSeasonalYears().sort((a,b)=>b-a),highlights=selectedSeasonalHighlights().sort((a,b)=>b-a);$('seasonalHighlightWrap').hidden=style!=='band';$('seasonalStats').hidden=style!=='band';renderSeasonalColorControls();traces=seasonalTraces(all,m,years,style,highlights,state.seasonalColors,$('seasonalShowAverage').checked,$('seasonalShowMedian').checked,cny?'cny':'calendar',payload.spring_festival_dates||{});traces.forEach(t=>{if(t.showlegend!==false)t.showlegend=true});const cnyAxis={range:[-60,345],tickvals:[-60,0,60,120,180,240,300],ticktext:['春节前60天','春节','春节后60天','春节后120天','春节后180天','春节后240天','春节后300天'],tickangle:0,showgrid:false,automargin:true};layout={margin:{l:72,r:34,t:48,b:48},hovermode:'closest',showlegend:true,legend:{orientation:'h',x:.5,xanchor:'center',y:1.02,yanchor:'bottom',font:{size:13}},xaxis:cny?cnyAxis:{range:['2000-01-01','2000-12-31'],...smartDateAxis(null,null,$('chart').clientWidth,true)},shapes:cny?[{type:'line',x0:0,x1:0,yref:'paper',y0:0,y1:1,line:{color:'#9aa3ad',width:1,dash:'dot'}}]:[],yaxis:yAxis('left'),plot_bgcolor:'#fff',paper_bgcolor:'#fff'}
  }else{const display=effectiveTimeRange($('startDate').value,end,state.series,$('endMode').value);$('effectiveRangeNote').textContent=(display.start&&display.end)?`实际显示：${display.start} → ${display.end}`:'';traces=state.series.map(s=>{const m=payload.metadata[s.indicator.indicator_id],seriesEnd=s.end_mode==='latest'?m.latest_date:s.end_date,transformed=moving((payload.series[s.indicator.indicator_id]||[]).filter(p=>(!s.start_date||p.date>=s.start_date)&&(!seriesEnd||p.date<=seriesEnd)),s.ma_days).map(p=>({...p,date:shiftedDate(p.date,s.shift_days)})),pts=pointsInViewport(transformed,display.start,display.end),color=s.axis==='right'?'red':'blue',name=(s.label||m.name)+(s.ma_days>1?` · MA${s.ma_days}`:'')+shiftLabel(s.shift_days);const t={x:pts.map(p=>p.date),y:pts.map(p=>p.value),name,showlegend:true,yaxis:s.axis==='right'?'y2':'y',customdata:pts.map(p=>[p.value_display||fmt(p.value)]),hovertemplate:`%{x|%Y-%m-%d}<br>%{customdata[0]}<extra></extra>`};return s.chart_type==='bar'?Object.assign(t,{type:'bar',marker:{color}}):Object.assign(t,{type:'scatter',mode:'lines',line:{color,width:s.axis==='right'?2:2.5}})});layout={margin:{l:76,r:76,t:48,b:48},hovermode:'closest',barmode:'group',showlegend:true,legend:{orientation:'h',x:.5,xanchor:'center',y:1.02,yanchor:'bottom',font:{size:13}},xaxis:{range:[display.start,display.end],...smartDateAxis(display.start,display.end,$('chart').clientWidth,false,$('dateTickInterval').value)},yaxis:yAxis('left'),yaxis2:{...yAxis('right'),overlaying:'y',side:'right'},plot_bgcolor:'#fff',paper_bgcolor:'#fff'}}Plotly.react('chart',traces,layout,{responsive:true,displaylogo:false,displayModeBar:false})}
function chartConfig(){const series=state.series.map(s=>({series_key:s.series_key,indicator_id:s.indicator.indicator_id,axis:s.axis,chart_type:s.chart_type,ma_days:s.ma_days,shift_days:s.shift_days||0,start_date:s.start_date,end_date:s.end_date,end_mode:s.end_mode,label:s.label})),indicator_ids=[...new Set(series.map(s=>s.indicator_id))].sort(),baseStart=$('startDate').value,baseEnd=resolvedEndDate(),mode=$('endMode').value,display=effectiveTimeRange(baseStart,baseEnd,state.series,mode);return{chart_id:state.chartId,chart_mode:$('chartMode').value,date_tick_interval:$('dateTickInterval').value,indicator_ids,indicator_combo_signature:indicator_ids.join('|'),title:$('chartTitle').value.trim()||'未命名图表',domain:$('chartDomain').value.trim()||'未分类',status:$('chartStatus').value,access_level:$('accessLevel').value,base_start_date:baseStart,base_end_date:baseEnd,start_date:display.start,end_date:display.end,end_mode:mode,seasonal_style:$('seasonalStyle').value,seasonal_years:selectedSeasonalYears(),seasonal_highlight_years:selectedSeasonalHighlights(),seasonal_show_average:$('seasonalShowAverage').checked,seasonal_show_median:$('seasonalShowMedian').checked,seasonal_colors:{...state.seasonalColors},left_axis:{min:numOrNull('leftMin'),max:numOrNull('leftMax'),reverse:$('leftReverse').checked},right_axis:{min:numOrNull('rightMin'),max:numOrNull('rightMax'),reverse:$('rightReverse').checked},series}}
function loadChart(chartId){const item=state.charts.find(x=>x.chart_id===chartId),c=item?.config;if(!c)return;state.chartId=c.is_default_single?null:item.chart_id;state.series=(c.series||[]).map(s=>{const indicator=state.indicators.find(x=>x.indicator_id===s.indicator_id);return indicator?newSeries(indicator,s):null}).filter(Boolean);$('chartTitle').value=c.is_default_single?`${item.title} · 自定义图`:item.title;state.lastAutoTitle=defaultChartTitle();state.titleManuallyEdited=true;$('chartMode').value=c.chart_mode||'timeseries';$('dateTickInterval').value=c.date_tick_interval||'auto';$('seasonalStyle').value=c.seasonal_style||'lines';$('seasonalYears').dataset.pending=JSON.stringify(c.seasonal_years||[]);$('seasonalHighlightYears').dataset.pending=JSON.stringify(c.seasonal_highlight_years||[]);$('seasonalShowAverage').checked=c.seasonal_show_average!==false;$('seasonalShowMedian').checked=c.seasonal_show_median!==false;state.seasonalColors={...(c.seasonal_colors||{})};$('chartDomain').value=item.domain||'未分类';$('chartStatus').value=item.status||'published';$('accessLevel').value=item.access_level||'private';$('startDate').value=c.base_start_date||c.start_date||'';$('endDate').value=c.base_end_date||c.end_date||'';$('endMode').value=c.end_mode||'latest';for(const side of ['left','right']){const a=c[`${side}_axis`]||{};$(`${side}Min`).value=a.min??'';$(`${side}Max`).value=a.max??'';$(`${side}Reverse`).checked=!!a.reverse}renderSelected();renderLibrary();refreshChart();switchView('workbench')}

function filteredCharts(){const q=$('gallerySearch').value.trim().toLowerCase(),k=$('galleryKind').value,d=$('galleryDomain').value;return state.charts.filter(x=>(!k||chartKind(x)===k)&&(!d||x.domain===d)&&(!q||[x.title,x.chart_id,x.domain,kindLabel(chartKind(x)),JSON.stringify(x.config||{})].join(' ').toLowerCase().includes(q)))}
function embedUrl(url){return url+(url.includes('?')?'&':'?')+'embed=1'}
function localFigureDocument(c,viewer=false){const fig=JSON.stringify(c.figure||{}).replace(/<\//g,'<\\/'),cfg=c.config||{},seasonal=cfg.chart_mode==='seasonal',dateAxis=JSON.stringify(smartDateAxis(cfg.start_date,cfg.end_date,viewer?1600:760,seasonal,cfg.date_tick_interval||'auto')),leftUnit=JSON.stringify(axisUnitForChart(c,'left')),rightUnit=JSON.stringify(axisUnitForChart(c,'right')),plotlySrc=STATIC_MODE?'https://cdn.plot.ly/plotly-3.0.1.min.js':'/static/vendor/plotly.min.js';return`<!doctype html><meta charset="utf-8"><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif}#chart{position:absolute;inset:0;width:100%;height:100%;min-height:0}</style><div id="chart"></div><script src="${plotlySrc}"><\/script><script>const fig=${fig},chart=document.getElementById('chart'),dateAxis=${dateAxis},leftUnit=${leftUnit},rightUnit=${rightUnit},base=fig.layout||{},layout={...base,autosize:true,showlegend:true,margin:${viewer?"{l:82,r:82,t:46,b:50}":"{l:72,r:72,t:42,b:46}"},
legend:{...(base.legend||{}),orientation:'h',x:.5,xanchor:'center',y:1.02,yanchor:'bottom',font:{size:13}},xaxis:{...(base.xaxis||{}),...dateAxis,showline:false,zeroline:false},yaxis:{...(base.yaxis||{}),showgrid:true,gridcolor:'#e8ebef',gridwidth:1,showline:false,zeroline:false,title:leftUnit?{text:leftUnit,standoff:8}:undefined},yaxis2:{...(base.yaxis2||{}),showgrid:false,showline:false,zeroline:false,title:rightUnit?{text:rightUnit,standoff:8}:undefined},hovermode:'closest',plot_bgcolor:'#fff',paper_bgcolor:'#fff'};delete layout.width;delete layout.height;(fig.data||[]).forEach(t=>{if(t.showlegend!==false)t.showlegend=true;t.hovertemplate=${seasonal?"'%{customdata[0]}<br>%{customdata[1]}<extra></extra>'":"'%{x|%Y-%m-%d}<br>%{y:,.8~f}<extra></extra>'"}});Plotly.newPlot(chart,fig.data||[],layout,{responsive:true,displaylogo:false,displayModeBar:false}).then(()=>{Plotly.Plots.resize(chart);chart.on('plotly_doubleclick',()=>parent.postMessage({type:'yd-open-chart',chartId:${JSON.stringify(c.chart_id)}},'*'))});new ResizeObserver(()=>Plotly.Plots.resize(chart)).observe(document.documentElement);<\/script>`}
function attachLocalFigures(root){root.querySelectorAll('iframe[data-local-chart]').forEach(f=>{const c=state.charts.find(x=>x.chart_id===f.dataset.localChart);if(c?.figure)f.srcdoc=localFigureDocument(c,false)})}
function frameGraph(frame){if(!frame)return null;try{return frame.contentDocument?.getElementById('chart')||null}catch{return null}}
function visibleAxisRange(graph,axis,start,end,reverse=false){const values=[];(graph?.data||[]).filter(t=>(t.yaxis||'y')===axis).forEach(t=>(t.y||[]).forEach((value,i)=>{const date=String((t.x||[])[i]||'').slice(0,10),number=Number(value);if(Number.isFinite(number)&&(!start||date>=start)&&(!end||date<=end))values.push(number)}));if(!values.length)return null;const lo=Math.min(...values),hi=Math.max(...values),pad=hi===lo?Math.max(Math.abs(lo)*.05,1):(hi-lo)*.06;return reverse?[hi+pad,lo-pad]:[lo-pad,hi+pad]}
function rangeUpdate(graph,c,values){const[start,end,lmin,lmax,rmin,rmax,tickInterval='auto']=values,u={},hasRight=(graph?.data||[]).some(t=>(t.yaxis||'y')==='y2');if(start&&end){u['xaxis.range']=[start,end];u['xaxis.autorange']=false;const dateAxis=smartDateAxis(start,end,graph?.clientWidth||window.innerWidth,false,tickInterval||'auto');for(const key of['tickformat','tickangle','nticks','automargin','dtick','tick0'])u[`xaxis.${key}`]=dateAxis[key]??null}else u['xaxis.autorange']=true;for(const[axis,lo,hi,side]of[['yaxis',lmin,lmax,'left'],['yaxis2',rmin,rmax,'right']]){if(axis==='yaxis2'&&!hasRight)continue;if(lo!==''&&hi!==''){u[`${axis}.range`]=[Number(lo),Number(hi)];u[`${axis}.autorange`]=false}else{const visible=visibleAxisRange(graph,axis==='yaxis'?'y':'y2',start,end,!!c.config?.[`${side}_axis`]?.reverse);if(visible){u[`${axis}.range`]=visible;u[`${axis}.autorange`]=false}else u[`${axis}.autorange`]=true}}return u}
async function applyFrameRange(frame,c,values){const graph=frameGraph(frame),lib=frame?.contentWindow?.Plotly;if(!graph||!lib)return false;await lib.relayout(graph,rangeUpdate(graph,c,values));return true}
async function previewFrameRange(c,frame,values){const ok=await applyFrameRange(frame,c,values);if(ok)showMessage('范围预览已更新；点击“应用范围”后才会保存并留痕。');return ok}
function lastValueAnnotations(graph){const range=graph?.layout?.xaxis?.range||[],start=range[0],end=range[1],numericRange=Number.isFinite(Number(start))&&Number.isFinite(Number(end)),out=[];(graph?.data||[]).forEach((trace,traceIndex)=>{if(trace.visible==='legendonly'||trace.showlegend===false||trace.fill==='tonexty')return;let hit=null;(trace.y||[]).forEach((value,i)=>{const x=(trace.x||[])[i],number=Number(value),visible=numericRange?Number(x)>=Number(start)&&Number(x)<=Number(end):(!start||String(x)>=String(start))&&(!end||String(x)<=String(end));if(Number.isFinite(number)&&visible)hit={x,y:number}});if(!hit)return;const color=trace.line?.color||trace.marker?.color||'#17212b';out.push({x:hit.x,y:hit.y,xref:'x',yref:(trace.yaxis||'y')==='y2'?'y2':'y',text:fmt(hit.y),showarrow:false,xanchor:'right',yanchor:'middle',xshift:-7,yshift:(traceIndex%3-1)*15,font:{size:12,color},bgcolor:'rgba(255,255,255,.88)',bordercolor:'rgba(255,255,255,0)',borderpad:2})});return out}
async function exportFrame(frame,filename,labelLast=false){const graph=frameGraph(frame),lib=frame?.contentWindow?.Plotly;if(!graph||!lib)return false;const original=Array.isArray(graph.layout?.annotations)?graph.layout.annotations:[];try{if(labelLast)await lib.relayout(graph,{annotations:[...original,...lastValueAnnotations(graph)]});const dataUrl=await lib.toImage(graph,{format:'png',width:1550,height:700,scale:2});const link=document.createElement('a');link.href=dataUrl;link.download=`${filename}.png`;document.body.appendChild(link);link.click();link.remove();return true}catch(error){console.error('PNG export failed',error);return false}finally{if(labelLast)await lib.relayout(graph,{annotations:original})}}
function rangeValue(value){return value===''||value==null?null:Number(value)}
function rangeConfig(c,values){const[start,end,lmin,lmax,rmin,rmax,tickInterval='auto']=values,cfg=JSON.parse(JSON.stringify(c.config||{}));cfg.chart_id=c.chart_id;cfg.title=c.title;cfg.domain=c.domain;cfg.status=c.status;cfg.access_level=c.access_level;cfg.base_start_date=start||cfg.start_date;cfg.base_end_date=end||cfg.end_date;cfg.start_date=start||cfg.start_date;cfg.end_date=end||cfg.end_date;cfg.end_mode='fixed';cfg.date_tick_interval=tickInterval||'auto';cfg.left_axis={...(cfg.left_axis||{}),min:rangeValue(lmin),max:rangeValue(lmax)};cfg.right_axis={...(cfg.right_axis||{}),min:rangeValue(rmin),max:rangeValue(rmax)};cfg._change_reason='chart_range_update';return cfg}
function portableFigure(graph){if(!graph)return null;try{return JSON.parse(JSON.stringify({data:graph.data,layout:graph.layout},(key,value)=>key.startsWith('_')?undefined:value))}catch{return null}}
async function saveFrameRange(c,frame,values,source='range'){if(!await applyFrameRange(frame,c,values))throw new Error('图表仍在加载，请稍后再应用。');const cfg=rangeConfig(c,values),graph=frameGraph(frame);if(STATIC_MODE)cfg.preview_figure=portableFigure(graph);const result=await getJSON('/api/charts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});c.config=rangeConfig(c,values);delete c.config._change_reason;await reloadCharts();const fresh=state.charts.find(x=>x.chart_id===c.chart_id);if(source==='viewer'&&frame?.isConnected&&fresh){frame.removeAttribute('srcdoc');frame.src='about:blank';frame.onload=()=>requestAnimationFrame(()=>{const g=frameGraph(frame),lib=frame.contentWindow?.Plotly;if(g&&lib)lib.Plots.resize(g)});requestAnimationFrame(()=>{if(fresh.html_url)frame.src=fresh.html_url+(fresh.html_url.includes('?')?'&':'?')+`embed=1&viewer=1&v=${Date.now()}`;else if(fresh.figure)frame.srcdoc=localFigureDocument(fresh,true);else frame.src=fresh.png_url||''})}showMessage(`已保存新默认范围并留存版本 V${String(result.version||1).padStart(3,'0')}。`);return result}
function fillViewerControls(c){const cfg=c.config||{},left=cfg.left_axis||{},right=cfg.right_axis||{};$('viewerStart').value=cfg.start_date||'';$('viewerEnd').value=cfg.end_date||'';$('viewerLeftMin').value=left.min??'';$('viewerLeftMax').value=left.max??'';$('viewerRightMin').value=right.min??'';$('viewerRightMax').value=right.max??'';$('viewerDateTick').value=cfg.date_tick_interval||'auto';$('viewerLabelLast').checked=false}
function openViewer(chartId,origin){const c=state.charts.find(x=>x.chart_id===chartId);if(!c)return;state.viewerOrigin=origin||'gallery';state.viewerChartId=chartId;$('viewerTitle').textContent=c.title;$('viewerMeta').textContent=`${c.chart_id} · ${kindLabel(chartKind(c))} · ${c.domain||'未分类'}`;fillViewerControls(c);const frame=$('viewerFrame');frame.removeAttribute('srcdoc');frame.src='about:blank';$('viewerExport').href='#';$('viewerExport').download=`${c.chart_id}.png`;$('viewerExport').style.display='inline-flex';$('chartViewer').showModal();frame.onload=()=>{requestAnimationFrame(()=>{const g=frameGraph(frame),lib=frame.contentWindow?.Plotly;if(g&&lib)lib.Plots.resize(g)})};requestAnimationFrame(()=>{if(c.html_url)frame.src=c.html_url+(c.html_url.includes('?')?'&':'?')+'embed=1&viewer=1';else if(c.figure)frame.srcdoc=localFigureDocument(c,true);else frame.src=c.png_url||''})}
function closeViewer(){$('chartViewer').close();$('viewerFrame').removeAttribute('srcdoc');$('viewerFrame').src='about:blank';switchView(state.viewerOrigin)}
function renderGallery(){const all=filteredCharts(),pages=Math.max(1,Math.ceil(all.length/state.galleryPageSize));state.galleryPage=Math.min(state.galleryPage,pages);const start=(state.galleryPage-1)*state.galleryPageSize,rows=all.slice(start,start+state.galleryPageSize);$('galleryCount').textContent=`${all.length} 张 · 第 ${state.galleryPage}/${pages} 页`;$('galleryGrid').innerHTML=rows.map(c=>`<article class="gallery-card" data-open-chart="${c.chart_id}" title="双击放大交互图">${c.figure?`<iframe data-local-chart="${c.chart_id}" title="${escapeHTML(c.title)}"></iframe>`:(c.png_url?`<img src="${c.png_url}" loading="lazy" decoding="async" alt="${escapeHTML(c.title)}">`:(c.html_url?`<iframe src="${embedUrl(c.html_url)}" loading="lazy" title="${escapeHTML(c.title)}"></iframe>`:'<div class="indicator-meta" style="aspect-ratio:15.5/7;display:grid;place-items:center">离线草稿预览</div>'))}<div class="gallery-name">${escapeHTML(c.title)}</div><div class="gallery-meta">${c.chart_id} · ${kindLabel(chartKind(c))} · ${escapeHTML(c.domain||'未分类')} · 更新 ${String(c.updated_at||'—').slice(0,16).replace('T',' ')}</div><div class="gallery-actions"><span><button class="text-button" data-view-chart="${c.chart_id}">放大查看</button> · <button class="text-button" data-edit-chart="${c.chart_id}">工作台编辑</button></span><label class="gallery-check"><input type="checkbox" data-chart="${c.chart_id}" ${state.showcase.has(c.chart_id)?'checked':''}>加入展示面板</label></div></article>`).join('')||'<div class="indicator-meta">没有符合条件的图表。</div>';$('galleryPager').innerHTML=all.length?`<button class="secondary" data-gallery-page="prev" ${state.galleryPage<=1?'disabled':''}>上一页</button><span>第 ${state.galleryPage} / ${pages} 页</span><button class="secondary" data-gallery-page="next" ${state.galleryPage>=pages?'disabled':''}>下一页</button>`:'';attachLocalFigures($('galleryGrid'));$('galleryGrid').querySelectorAll('[data-chart]').forEach(x=>x.onchange=()=>{x.checked?state.showcase.add(x.dataset.chart):state.showcase.delete(x.dataset.chart);persistShowcase()});$('galleryGrid').querySelectorAll('[data-edit-chart]').forEach(x=>x.onclick=e=>{e.stopPropagation();loadChart(x.dataset.editChart)});$('galleryGrid').querySelectorAll('[data-view-chart]').forEach(x=>x.onclick=e=>{e.stopPropagation();openViewer(x.dataset.viewChart,'gallery')});$('galleryGrid').querySelectorAll('[data-open-chart]').forEach(x=>x.ondblclick=()=>openViewer(x.dataset.openChart,'gallery'));$('galleryPager').querySelectorAll('[data-gallery-page]').forEach(x=>x.onclick=()=>{state.galleryPage+=x.dataset.galleryPage==='next'?1:-1;renderGallery();window.scrollTo({top:0,behavior:'smooth'})});$('showcaseCount').textContent=state.showcase.size}
function persistShowcase(){localStorage.setItem('yd-showcase',JSON.stringify([...state.showcase]));$('showcaseCount').textContent=state.showcase.size;renderShowcase()}
function selectedShowcaseCharts(){const q=$('showcaseSearch')?.value.trim().toLowerCase()||'',k=$('showcaseKind')?.value||'',d=$('showcaseDomain')?.value||'';return state.charts.filter(c=>state.showcase.has(c.chart_id)&&(!k||chartKind(c)===k)&&(!d||c.domain===d)&&(!q||[c.title,c.chart_id,c.domain,JSON.stringify(c.config||{})].join(' ').toLowerCase().includes(q)))}
function renderShowcasePicker(){const el=$('showcasePickerResults'),q=$('showcaseSearch').value.trim().toLowerCase(),k=$('showcaseKind').value,d=$('showcaseDomain').value;if(!q){el.innerHTML='<div class="indicator-meta">输入图名、图表ID、指标ID或板块，匹配结果会在这里显示并可直接勾选。</div>';return}const rows=state.charts.filter(c=>(!k||chartKind(c)===k)&&(!d||c.domain===d)&&[c.title,c.chart_id,c.domain,kindLabel(chartKind(c)),JSON.stringify(c.config||{})].join(' ').toLowerCase().includes(q)).slice(0,80);el.innerHTML=rows.map(c=>`<label class="showcase-pick-item"><input type="checkbox" data-pick-chart="${c.chart_id}" ${state.showcase.has(c.chart_id)?'checked':''}><span><strong>${escapeHTML(c.title)}</strong><span>${c.chart_id} · ${kindLabel(chartKind(c))} · ${escapeHTML(c.domain||'未分类')}</span></span></label>`).join('')||'<div class="indicator-meta">没有匹配图片。</div>';el.querySelectorAll('[data-pick-chart]').forEach(x=>x.onchange=()=>{x.checked?state.showcase.add(x.dataset.pickChart):state.showcase.delete(x.dataset.pickChart);localStorage.setItem('yd-showcase',JSON.stringify([...state.showcase]));$('showcaseCount').textContent=state.showcase.size;renderShowcase();renderGallery()})}
function showcaseRangeHTML(c){const cfg=c.config||{},l=cfg.left_axis||{},r=cfg.right_axis||{},tick=cfg.date_tick_interval||'auto';return`<div class="showcase-range-controls"><label>开始<input class="sc-start" type="date" value="${cfg.start_date||''}"></label><label>结束<input class="sc-end" type="date" value="${cfg.end_date||''}"></label><label>左轴最小<input class="sc-lmin" inputmode="decimal" placeholder="自动" value="${l.min??''}"></label><label>左轴最大<input class="sc-lmax" inputmode="decimal" placeholder="自动" value="${l.max??''}"></label><label>右轴最小<input class="sc-rmin" inputmode="decimal" placeholder="自动" value="${r.min??''}"></label><label>右轴最大<input class="sc-rmax" inputmode="decimal" placeholder="自动" value="${r.max??''}"></label><label>日期标注<select class="sc-tick"><option value="auto" ${tick==='auto'?'selected':''}>自动</option><option value="6m" ${tick==='6m'?'selected':''}>半年</option><option value="1y" ${tick==='1y'?'selected':''}>1年</option><option value="2y" ${tick==='2y'?'selected':''}>2年</option><option value="5y" ${tick==='5y'?'selected':''}>5年</option></select></label><label class="axis-direction-toggle"><input class="sc-label-last" type="checkbox"><span>导出标注末值</span></label><button class="apply-range">应用</button><button data-view-chart="${c.chart_id}">全屏</button><button class="export-current">导出PNG</button></div>`}
function bindShowcaseItem(item,c){const frame=item.querySelector('iframe'),values=()=>['.sc-start','.sc-end','.sc-lmin','.sc-lmax','.sc-rmin','.sc-rmax','.sc-tick'].map(s=>item.querySelector(s).value);item.querySelectorAll('.showcase-range-controls input:not(.sc-label-last),.showcase-range-controls select').forEach(input=>input.onchange=()=>previewFrameRange(c,frame,values()).catch(error=>showMessage(error.message,true)));item.querySelector('.apply-range').onclick=async e=>{e.stopPropagation();try{e.currentTarget.disabled=true;await saveFrameRange(c,frame,values(),'showcase')}catch(error){showMessage(error.message,true)}finally{if(e.currentTarget)e.currentTarget.disabled=false}};item.querySelector('.export-current').onclick=async e=>{e.stopPropagation();if(!await exportFrame(frame,c.chart_id,item.querySelector('.sc-label-last').checked))showMessage('图表仍在加载，请稍后再导出。',true)}}
function renderShowcase(){const all=state.charts.filter(c=>state.showcase.has(c.chart_id)),domains=[...new Set(state.charts.map(c=>c.domain||'未分类'))].sort(),domainEl=$('showcaseDomain'),currentDomain=domainEl?.value||'';if(domainEl){while(domainEl.options.length>1)domainEl.remove(1);domains.forEach(v=>domainEl.add(new Option(v,v)));domainEl.value=domains.includes(currentDomain)?currentDomain:''}renderShowcasePicker();const charts=selectedShowcaseCharts();$('showcaseSummary').textContent=all.length?`已选择 ${all.length} 张图片 · 当前显示 ${charts.length} 张`:'尚未选择图片';const jump=$('showcaseJump');if(jump)jump.innerHTML='<option value="">选择图名或ID</option>'+charts.map(c=>`<option value="${c.chart_id}">${escapeHTML(c.title)} · ${c.chart_id}</option>`).join('');$('showcaseNavList').innerHTML=charts.map(c=>`<button class="showcase-nav-button" data-jump="${c.chart_id}">${escapeHTML(c.title)}<br><span class="indicator-meta">${c.chart_id}</span></button>`).join('');$('showcaseGrid').innerHTML=charts.map(c=>`<article class="showcase-item" id="showcase-${c.chart_id}" data-open-chart="${c.chart_id}"><div class="showcase-title"><span>${escapeHTML(c.title)} · ${c.chart_id}</span><button data-remove="${c.chart_id}">移除</button></div>${showcaseRangeHTML(c)}${c.html_url?`<iframe src="${embedUrl(c.html_url)}" loading="lazy" title="${escapeHTML(c.title)}"></iframe>`:(c.figure?`<iframe data-local-chart="${c.chart_id}" title="${escapeHTML(c.title)}"></iframe>`:(c.png_url?`<img src="${c.png_url}" alt="${escapeHTML(c.title)}" style="width:100%;aspect-ratio:15.5/7;object-fit:contain">`:'<div class="indicator-meta">暂无预览。</div>'))}</article>`).join('');attachLocalFigures($('showcaseGrid'));const jumpTo=id=>document.getElementById(`showcase-${id}`)?.scrollIntoView({behavior:'smooth',block:'start'});$('showcaseNavList').querySelectorAll('[data-jump]').forEach(x=>x.onclick=()=>jumpTo(x.dataset.jump));if(jump)jump.onchange=()=>jump.value&&jumpTo(jump.value);$('showcaseGrid').querySelectorAll('.showcase-item').forEach(item=>{const c=state.charts.find(x=>x.chart_id===item.dataset.openChart);if(c)bindShowcaseItem(item,c)});$('showcaseGrid').querySelectorAll('[data-view-chart]').forEach(x=>x.onclick=e=>{e.stopPropagation();openViewer(x.dataset.viewChart,'showcase')});$('showcaseGrid').querySelectorAll('[data-open-chart]').forEach(x=>x.ondblclick=e=>{if(!e.target.closest('.showcase-range-controls'))openViewer(x.dataset.openChart,'showcase')});$('showcaseGrid').querySelectorAll('[data-remove]').forEach(x=>x.onclick=e=>{e.stopPropagation();state.showcase.delete(x.dataset.remove);persistShowcase();renderGallery()})}
async function reloadCharts(){state.charts=await getJSON('/api/charts');hydrateLocalFigures();populateFilters(await getJSON('/api/domains'));renderGallery();renderShowcase()}
function sameIndicatorCombo(a,b){const key=c=>[...new Set((c.series||[]).map(s=>s.indicator_id))].sort().join('|');return key(a)===key(b)}
function duplicateDecision(matches){return new Promise(resolve=>{const d=$('duplicateDialog');$('duplicateText').textContent=`这两个指标的组合已经对应唯一图表：${matches.map(x=>`${x.title}（${x.chart_id}）`).join('；')}。继续将更新已有图并生成新版本，不会创建重复ID。`;$('duplicateUpdate').onclick=()=>{d.close();resolve({action:'update',chart:matches[0]})};$('duplicateCancel').onclick=()=>{d.close();resolve({action:'cancel'})};d.showModal()})}
function showImportStatus(text,error=false){const el=$('importStatus');if(el){el.textContent=text;el.style.color=error?'#b42318':'#4d5a69'}showMessage(text,error)}
async function runImport(mode='existing_only'){if(mode==='full_audit'&&!window.confirm('完整历史审计会重新读取全部 Excel 的全部历史。原始 Excel 不会被修改。是否继续？'))return;const buttons=[$('updateExisting'),$('quickExisting'),$('discoverNew'),$('fullAudit')].filter(Boolean);buttons.forEach(x=>x.disabled=true);switchView('pipeline');const running={existing_only:'正在快速更新已有指标，只读取近期尾部数据…',discover_new:'正在更新已有指标并检查新指标…',full_audit:'正在完整审计全部 Excel 历史，请不要关闭正式工作台…'};showImportStatus(running[mode]);try{const r=await getJSON('/api/run-import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,user_initiated:true,trigger:'manual_update_button'})});if(!r.ok)throw new Error(r.error||'更新失败。');await reloadAll();const t=r.totals||{};let summary;if(mode==='existing_only')summary=`已有指标更新完成：新增或修订 ${Number(t.changed||0).toLocaleString()} 个数据点，跳过 ${Number(t.new_indicators_skipped||0).toLocaleString()} 个陌生指标。`;else if(mode==='discover_new')summary=`更新与发现完成：新增 ${Number(t.new_indicators_added||0).toLocaleString()} 个指标，新增或修订 ${Number(t.changed||0).toLocaleString()} 个数据点。`;else summary=`完整历史审计完成：读取 ${Number(t.files_imported||0).toLocaleString()} 个文件，新增或修订 ${Number(t.changed||0).toLocaleString()} 个数据点。`;showImportStatus(summary)}catch(e){showImportStatus(e.message,true)}finally{buttons.forEach(x=>x.disabled=false)}}
function bindControls(){document.querySelectorAll('.nav-button').forEach(x=>x.onclick=()=>switchView(x.dataset.view));$('openShowcase').onclick=()=>switchView('showcase');$('clearShowcase').onclick=()=>{state.showcase.clear();persistShowcase();renderGallery()};$('gallerySearch').oninput=()=>{state.galleryPage=1;renderGallery()};$('galleryKind').onchange=()=>{state.galleryPage=1;populateGalleryDomains();renderGallery()};$('galleryDomain').onchange=()=>{state.galleryPage=1;renderGallery()};$('search').oninput=()=>{state.indicatorLimit=80;renderLibrary()};$('domainFilter').onchange=()=>{state.indicatorLimit=80;renderLibrary()};$('frequencyFilter').onchange=()=>{state.indicatorLimit=80;renderLibrary()};$('indicatorMore').onclick=()=>{state.indicatorLimit+=80;renderLibrary()};$('showcaseSearch').oninput=renderShowcase;$('showcaseKind').onchange=renderShowcase;$('showcaseDomain').onchange=renderShowcase;$('derivedIndicatorSearch').oninput=renderDerivedSearch;$('chartTitle').oninput=()=>{state.titleManuallyEdited=$('chartTitle').value.trim()!==state.lastAutoTitle};$('viewerBack').onclick=closeViewer;
$('viewerApply').onclick=async e=>{const c=state.charts.find(x=>x.chart_id===state.viewerChartId),values=[$('viewerStart').value,$('viewerEnd').value,$('viewerLeftMin').value,$('viewerLeftMax').value,$('viewerRightMin').value,$('viewerRightMax').value,$('viewerDateTick').value];if(!c)return;try{e.currentTarget.disabled=true;const result=await saveFrameRange(c,$('viewerFrame'),values,'viewer');$('viewerMeta').textContent=`${c.chart_id} · ${kindLabel(chartKind(c))} · ${c.domain||'未分类'} · 已留存 V${String(result.version||1).padStart(3,'0')}`}catch(error){showMessage(error.message,true)}finally{e.currentTarget.disabled=false}};
['viewerStart','viewerEnd','viewerLeftMin','viewerLeftMax','viewerRightMin','viewerRightMax','viewerDateTick'].forEach(id=>$(id).onchange=()=>{const c=state.charts.find(x=>x.chart_id===state.viewerChartId);if(!c)return;const values=[$('viewerStart').value,$('viewerEnd').value,$('viewerLeftMin').value,$('viewerLeftMax').value,$('viewerRightMin').value,$('viewerRightMax').value,$('viewerDateTick').value];previewFrameRange(c,$('viewerFrame'),values).catch(error=>showMessage(error.message,true))});
  $('viewerExport').onclick=async e=>{e.preventDefault();const c=state.charts.find(x=>x.chart_id===state.viewerChartId);if(!await exportFrame($('viewerFrame'),c?.chart_id||'chart',$('viewerLabelLast').checked))showMessage('图表仍在加载，请稍后再导出。',true)};$('viewerEdit').onclick=()=>{const id=state.viewerChartId;$('chartViewer').close();$('viewerFrame').removeAttribute('srcdoc');$('viewerFrame').src='about:blank';if(id)loadChart(id)};$('chartViewer').addEventListener('cancel',e=>{e.preventDefault();closeViewer()});window.addEventListener('message',e=>{if(e.data?.type==='yd-close-viewer'&&$('chartViewer').open)closeViewer();if(e.data?.type==='yd-open-chart'&&state.charts.some(c=>c.chart_id===e.data.chartId))openViewer(e.data.chartId,document.getElementById('showcaseView').classList.contains('active')?'showcase':'gallery')});$('clearSelection').onclick=()=>{state.series=[];state.titleManuallyEdited=false;state.lastAutoTitle='';$('chartTitle').value='未命名图表';renderLibrary();renderSelected();refreshChart()};['startDate','leftMin','leftMax','rightMin','rightMax','leftReverse','rightReverse','chartMode','dateTickInterval','seasonalStyle','seasonalYears','seasonalHighlightYears','seasonalShowAverage','seasonalShowMedian'].forEach(id=>$(id).onchange=refreshChart);$('endDate').onchange=()=>{$('endMode').value='fixed';refreshChart()};$('endMode').onchange=()=>{if($('endMode').value!=='fixed')$('endDate').value=resolvedEndDate();refreshChart()};document.querySelectorAll('[data-years]').forEach(b=>b.onclick=()=>{if(!state.series.length)return;const d=new Date(`${resolvedEndDate()}T00:00:00`);if(b.dataset.years==='all')$('startDate').value=state.series.map(x=>x.indicator.first_date).filter(Boolean).sort()[0];else{d.setFullYear(d.getFullYear()-Number(b.dataset.years));$('startDate').value=d.toISOString().slice(0,10)}refreshChart()});
  $('saveChart').onclick=async()=>{if(!state.series.length)return showMessage('请先选择指标。',true);try{const config=chartConfig();if(!config.chart_id&&chartKind({config})==='dual'){const matches=state.charts.filter(c=>chartKind(c)==='dual'&&sameIndicatorCombo(c.config,config));if(matches.length){const choice=await duplicateDecision(matches);if(choice.action==='cancel')return;if(choice.action==='update'){config.chart_id=choice.chart.chart_id;state.chartId=choice.chart.chart_id}}}if(STATIC_MODE){config.preview_data_url=await Plotly.toImage($('chart'),{format:'png',width:1550,height:700});config.preview_figure={data:$('chart').data,layout:$('chart').layout}}const r=await getJSON('/api/charts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});state.chartId=r.chart_id;await reloadCharts();showMessage(r.preview_mode?`已加入离线图库：${r.chart_id}。`:`已加入图库：${r.chart_id}，图库已同步。`);switchView('gallery')}catch(e){showMessage(e.message,true)}};
  $('saveDerived').onclick=async()=>{const config=derivedConfig();if(!config.name)return $('derivedMessage').textContent='请填写指标名称。';if(!config.inputs.length)return $('derivedMessage').textContent='至少加入一个公式输入。';if(config.operation==='custom'&&!config.expression)return $('derivedMessage').textContent='请填写自定义公式。';try{$('saveDerived').disabled=true;$('derivedMessage').textContent='正在计算并写入指标库…';const r=await getJSON('/api/derived',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});resetDerivedForm();await reloadAll();$('derivedMessage').textContent=`已生成 ${r.indicator_id}，共 ${Number(r.observations).toLocaleString()} 个观察值。可以继续构建下一个指标。`}catch(e){$('derivedMessage').textContent=e.message}finally{$('saveDerived').disabled=false}};
  if($('updateExisting'))$('updateExisting').onclick=()=>runImport('existing_only');$('quickExisting').onclick=()=>runImport('existing_only');$('discoverNew').onclick=()=>runImport('discover_new');$('fullAudit').onclick=()=>runImport('full_audit')
}
function showMessage(t,error=false){$('message').textContent=t;$('message').style.color=error?'#b42318':'#4d5a69'}function escapeHTML(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const baseRenderPipeline=renderPipeline;renderPipeline=function(){baseRenderPipeline();const labels={existing_only:'更新已有指标',discover_new:'更新并发现新指标',full_audit:'完整历史审计',incremental:'智能增量'};document.querySelectorAll('#workbookStates tbody tr').forEach((row,i)=>{const item=state.pipeline?.workbooks?.[i];if(item&&row.children[1])row.children[1].textContent=labels[item.last_mode]||item.last_mode||'—'})}

const publicHydrateLocalFigures=hydrateLocalFigures;
let publicPlotlyPromise=null;
function ensurePublicPlotly(){
  if(window.Plotly)return Promise.resolve(window.Plotly);
  if(publicPlotlyPromise)return publicPlotlyPromise;
  publicPlotlyPromise=new Promise((resolve,reject)=>{
    const script=document.createElement('script');
    script.src='https://cdn.plot.ly/plotly-3.0.1.min.js';
    script.async=true;
    script.onload=()=>resolve(window.Plotly);
    script.onerror=()=>reject(new Error('图表组件加载失败，请检查网络后重试。'));
    document.head.appendChild(script);
  });
  return publicPlotlyPromise;
}
hydrateLocalFigures=function(){
  if(window.GALLERY_BOOTSTRAP?.series)publicHydrateLocalFigures();
};
async function ensurePublicChartFigure(chart){
  if(!STATIC_MODE||chart?.figure||!chart?.config?.series?.length)return;
  await ensurePublicPlotly();
  const config=chart.config||{};
  const ids=[...new Set((config.series||[]).map(item=>item.indicator_id).filter(Boolean))];
  if(!ids.length)return;
  const seasonal=config.chart_mode==='seasonal'||config.chart_mode==='seasonal_cny';
  const seasonalYears=(config.seasonal_years||[]).map(Number).filter(Number.isFinite);
  const starts=(config.series||[]).map(item=>item.start_date).filter(Boolean).sort();
  const ends=(config.series||[]).map(item=>item.end_date).filter(Boolean).sort();
  const start=seasonal
    ?(seasonalYears.length?Math.min(...seasonalYears)+'-01-01':state.indicators.find(item=>item.indicator_id===ids[0])?.first_date||'2010-01-01')
    :(config.start_date||starts[0]||'2010-01-01');
  const latest=ids.map(id=>state.indicators.find(item=>item.indicator_id===id)?.latest_date).filter(Boolean).sort().pop();
  const end=seasonal
    ?(seasonalYears.length?Math.max(...seasonalYears)+'-12-31':latest||'9999-12-31')
    :(config.end_mode==='latest'?(latest||'9999-12-31'):(config.end_date||ends.pop()||latest||'9999-12-31'));
  const payload=await getJSON(`/api/series?${new URLSearchParams({ids:ids.join(','),start,end})}`);
  const bootstrap=window.GALLERY_BOOTSTRAP;
  const oldSeries=bootstrap.series;
  const oldCharts=state.charts;
  bootstrap.series=payload.series;
  state.charts=[chart];
  try{publicHydrateLocalFigures()}finally{
    state.charts=oldCharts;
    bootstrap.series=oldSeries;
  }
}
const publicOpenViewer=openViewer;
openViewer=async function(chartId,origin){
  const chart=state.charts.find(item=>item.chart_id===chartId);
  try{await ensurePublicChartFigure(chart)}
  catch(error){showMessage(error.message,true);return}
  return publicOpenViewer(chartId,origin);
};
const publicLoadChart=loadChart;
loadChart=async function(chartId){
  await ensurePublicPlotly();
  return publicLoadChart(chartId);
};

initialize().catch(e=>{$('systemStats').textContent='公开目录加载失败';showMessage(e.message,true)});
